version: "3.7"

services:
  bitcoind:
    container_name: bitcoind
    image: getumbrel/bitcoind:v28.0
    command: "${APP_BITCOIN_COMMAND}"
    restart: unless-stopped
    user: "${APP_BITCOIND_USER_INFO}"
    stop_grace_period: 15m30s
    ports:
      - "${APP_BITCOIND_P2P_PORT}:${APP_BITCOIND_P2P_PORT}"
      - "${APP_BITCOIND_RPC_PORT}:${APP_BITCOIND_RPC_PORT}"
    volumes:
      - "../volumes/bitcoin/node:/data/.bitcoin"
    networks:
      default:
        ipv4_address: "${APP_BITCOIND_IP}"
